version: '3.7'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      PORT: '3000'
      MONGO_URL: 'mongodb://root:pass@task-mongo:27017/task-master?authSource=admin'
      MONGO_DATABASE: 'task-master'
    depends_on:
      - task-mongo

  task-mongo:
    image: mongo:latest
    container_name: task-mongo
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=task-master
    expose:
      - 27017
    ports:
      - 27017:27017
    restart: unless-stopped

volumes:
  mongo-data:
